import React, { FC } from 'react';

import { Container, Row } from 'react-bootstrap';
import { LinkContainer } from 'react-router-bootstrap';

import { ExamplesPageProps, ExamplesStorybookPageProps, ExamplesSubPageProps } from './Example.types';
import { BannerNavBar, Footer, NavbarLinkProperty } from '..';

import { PallasPageWrapper } from '../PallasPageWrapper/PallasPageWrapper.components';

/**
 *
 * @param param0
 * @returns
 */
export const ExamplesHeadPage: FC<ExamplesPageProps> = ({ footerProps, navBarProps, exampleProps }) => {
  return (
    <PallasPageWrapper authenticated={true} footerProps={footerProps} navBarProps={navBarProps}>
      <Container id='intro' className={'my-2'}>
        <Row>
          <h1>Examples</h1>
        </Row>
        <Row>
          <p>This section provides a number of examples to help you quickly get started using the library.</p>
        </Row>
        {exampleProps.map((exampleProp: NavbarLinkProperty) => {
          return <ExamplesHeadTitlePage {...exampleProp} />;
        })}
      </Container>
    </PallasPageWrapper>
  );
};

/**
 *
 * @param param0
 * @returns
 */
export const ExamplesSectionPage: FC<ExamplesSubPageProps> = ({ footerProps, navBarProps, exampleProps }) => {
  return (
    <PallasPageWrapper authenticated={true} footerProps={footerProps} navBarProps={navBarProps}>
      <Container id='intro' className={'my-2'}>
        <ExamplesHeadTitlePage {...exampleProps} />
      </Container>
    </PallasPageWrapper>
  );
};

/**
 * Used to generate
 * @param param0
 * @returns
 */
export const ExamplesHeadTitlePage: FC<NavbarLinkProperty> = ({ text, items }) => {
  return (
    <>
      {items ? (
        <>
          <Row className={'mx-3'}>
            <h2>{text}</h2>
          </Row>
          <Row className={'mx-3'}>
            <ul>
              {items.map((item) => {
                return (
                  <>
                    {item.path ? (
                      <li>
                        <LinkContainer to={item.path}>
                          <a>{item.text}</a>
                        </LinkContainer>
                      </li>
                    ) : (
                      <p>test</p>
                    )}
                  </>
                );
              })}
            </ul>
          </Row>
        </>
      ) : null}
    </>
  );
};

/**
 * This is used to generate a page to wrap stories generated by storybook.
 * @param param0 - the page footer and navbar properties as well as information to load the storybook id.
 * @returns a valid storybook page.
 */
export const ExamplesStorybookPage: FC<ExamplesStorybookPageProps> = ({ footerProps, navBarProps, exampleProps }) => {
  const srcLink = './storybook-static/iframe.html?id=' + exampleProps.id + '&viewMode=docs&shortcuts=false';

  return (
    <PallasPageWrapper authenticated={true} footerProps={footerProps} navBarProps={navBarProps}>
      <iframe
        className='embed-responsive-item'
        src={srcLink}
        height='100%'
        width='100%'
        style={{ minHeight: '1150px' }}
      />
    </PallasPageWrapper>
  );
};
