name: Build Verification for docs of the Node.JS project

on:
  create:
    branches:
      - 'release/*'
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: PallasSystems/infrastructure-ci/.github/workflows/nodejs_npm_docs_build_analysis@main
    secrets: inherit
