name: Check Node.JS version support

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: PallasSystems/infrastructure-ci/.github/workflows/nodejs/nodejs_npm_check_version_support.yml@main
    secrets: inherit
