name: Release Docs of NPM project

on:
  create:
    branches:
      - 'release/*'
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: PallasSystems/infrastructure-ci/.github/workflows/nodejs_npm_docs_release_on_branch@main
    secrets: inherit
