name: Release NPM project

on:
  create:
    branches:
      - 'release/*'
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  checks: write
  id-token: write
  issues: write
  packages: write
  pages: write
  pull-requests: write

jobs:
  nodejs_npm_release_on_branch:
    uses: PallasSystems/infrastructure-ci/.github/workflows/nodejs_npm_release_on_branch.yml@main
    secrets: inherit
  nodejs_npm_docs_release_on_branch:
    uses: PallasSystems/infrastructure-ci/.github/workflows/nodejs_npm_docs_release_on_branch.yml@main
    secrets: inherit
