name: Release NPM project

on:
  create:
    branches:
      - 'release/*'
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: PallasSystems/infrastructure-ci/.github/workflows/nodejs_npm_release_on_branch.yml@main
    secrets: inherit
